repository: decaprime/vrising-modding

collections:
  prefabs:
    permalink: "/prefabs/:name/"
    output: true

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-remote-theme
- jemoji
- jekyll-coffeescript
- jekyll-default-layout
- jekyll-gist
- jekyll-optional-front-matter
- jekyll-paginate
- sass
- jekyll-readme-index
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-include-cache


remote_theme: just-the-docs/just-the-docs@v0.10.0
color_scheme: vampire


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/decaprime/vrising-modding" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

title: V Rising Mod Wiki
description: "Information about mods for the game V Rising: How to setup on Windows / Linux. Developer information. How to build, debug, and publish your mods."

heading_anchors: true

aux_links:
  "Join our Discord":
    - "https://vrisingmods.com/discord"

nav_external_links:
  - title: Join our Discord
    url: https://vrisingmods.com/discord
    hide_icon: true
  - title: âž• Add new page
    url: https://github.com/decaprime/vrising-modding/new/main/dev?filename=FILE_NAME.md&value=---%0Atitle%3A%20YOUR%20TITLE%20HERE%20%28i.e.%20page%20title%29%0Aparent%3A%20PARENT%20DOC%20TITLE%20%28e.g.%20For%20Developers%29%0A---%0A%0A1.%20Update%20the%20FILE_NAME%20and%20path%20above%20the%20editor%0A2.%20Set%20the%20title%20and%20parent%20at%20top%20of%20this%20doc%20%0A3.%20You%20can%20find%20more%20info%3A%20https%3A%2F%2Fjust-the-docs.github.io%2Fjust-the-docs%2Fdocs%2Fnavigation-structure%2F%20%0A4.%20After%20you%27re%20done%2C%20scroll%20down%20and%20please%20start%20a%20pull%20request%20%F0%9F%98%8A%0A5.%20Replace%20these%20instructions%20with%20your%20wiki%20content%20in%20markdown
    hide_icon: true # set to true to hide the external link icon - defaults to false

enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red
  grey-lt:
    title: Note
    color: grey-lt
  yellow:
    title: Note
    color: yellow
  green:
    title: Note
    color: green

search_enabled: true
search.heading_level: 4
search.tokenizer: /[\s/_-]+/
focus_shortcut_key: 'k'
